### ISSUE TITLE
Error con version de parallelshell en node 10

### ISSUE THREAD

**Issue by ArnoldLC** [jonmircha/kenai-npm-starter-kit#2]
Luego de instalar todos los paquetes correctamente, al ejecutar el comando **npm start** me dio el siguiente error:
npm start

> kenai-npm-starter-kit@1.0.0 start D:\Git\ingenieria-web
> npm run devserve

> kenai-npm-starter-kit@1.0.0 devserve D:\Git\ingenieria-web
> parallelshell "npm run metalangs" "npm run serve"

child_process.js:413
    throw new ERR_INVALID_ARG_TYPE('options.cwd', 'string', options.cwd);
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "options.cwd" property must be of type string. Received type function
    at normalizeSpawnArguments (child_process.js:413:11)
    at exports.spawn (child_process.js:515:38)
    at D:\Git\ingenieria-web\node_modules\parallelshell\index.js:104:17
    at Array.forEach (<anonymous>)
    at Object.<anonymous> (D:\Git\ingenieria-web\node_modules\parallelshell\index.js:100:6)
    at Module._compile (internal/modules/cjs/loader.js:678:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
    at Module.load (internal/modules/cjs/loader.js:589:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
    at Function.Module._load (internal/modules/cjs/loader.js:520:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! kenai-npm-starter-kit@1.0.0 devserve: `parallelshell "npm run metalangs" "npm run serve"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the kenai-npm-starter-kit@1.0.0 devserve script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Arnold\AppData\Roaming\npm-cache\_logs\2018-06-25T04_22_22_500Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! kenai-npm-starter-kit@1.0.0 start: `npm run devserve`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the kenai-npm-starter-kit@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Arnold\AppData\Roaming\npm-cache\_logs\2018-06-25T04_22_23_119Z-debug.log

_**Investigando un poco, al parecer es un error de la versión del paquete con la versión de node. No son compatibles al parecer**_

**Comment by ArnoldLC** [comment]
La solución a este error fue cambiando la versión de este paquete con el comando.
**npm install parallelshell@3.0.1**

**Comment by larr86** [comment]
There is a problem with **Parallelshell** that has to be fixed manually;

go to the file:

`node_modules/parallelshell/index.js`
Then change this line:

`cwd: process.versions.node < '8.0.0' ? process.cwd : process.cwd(),`
To this:

`cwd: parseInt(process.versions.node) < 8 ? process.cwd : process.cwd(),`
It's done!
